export enum VoteSegment__Enum {
  POST = 'POST',
  POST_COMMENT = 'POST_COMMENT',
  POST_MEDIA = 'POST_MEDIA',
  //community
  COMMUNITY_QNA = 'COMMUNITY_QNA',
  COMMUNITY_QNA_RESPONSE = 'COMMUNITY_QNA_RESPONSE',
  GROUP_CHAT = 'GROUP_CHAT',
  GROUP_CHAT_MESSAGE = 'GROUP_CHAT_MESSAGE',
  TAG = 'TAG',
  THOUGHT = 'THOUGHT',
  THOUGHT_MEDIA = 'THOUGHT_MEDIA',
  THOUGHT_COMMENT = 'THOUGHT_COMMENT',
}

export enum VoteType__Enum {
  UP = 'UP',
  DOWN = 'DOWN',
  NEUTRAL = 'NEUTRAL',
  HELPFUL = 'HELPFUL',
  NOT_HELPFUL = 'NOT_HELPFUL',
}
