//  ==============================================Entity types
export enum EntityRoleType__Enum {
    SUPER_ADMIN = "SUPER_ADMIN",
    ADMINISTRATOR = "ADMINISTRATOR",
    EDITOR = "EDITOR",
    AUTHOR = "AUTHOR",
    CONTRIBUTOR = "CONTRIBUTOR",
    SUBSCRIBER = "SUBSCRIBER",
    VIEWER = "VIEWER",
  }
  
  export enum EntityUserPositionType__Enum {
    OWNER = "OWNER",
    MANAGER = "MANAGER",
    STAFF = "STAFF",
  }
  export enum EntityType__Enum {
    BUSINESS = "BUSINESS",
    SOCIAL_ORGANIZATION = "SOCIAL_ORGANIZATION",
    NON_GOVERNMENTAL_ORGANIZATION = "NON_GOVERNMENTAL_ORGANIZATION",
    CIVIC_ORGANIZATION = "CIVIC_ORGANIZATION",
    ACADEMIC_INSTITUTION = "ACADEMIC_INSTITUTION",
    GUILD = "GUILD",
    FREE_LANCER ="FREE_LANCER",
    PERSONAL_BRAND = "PERSONAL_BRAND",
    PROFESSIONAL_ASSOCIATION = "PROFESSIONAL_ASSOCIATION",
    GROUP = "GROUP",
    OTHER = "OTHER",
  }